            - name: Pip Installer
  # You may pin to the exact commit or the version.
  # uses: BSFishy/pip-action@8f2d471d809dc20b6ada98c91910b6ae6243f318
  uses: BSFishy/pip-action@v1
  with:
    # The packages to install from Pip
    packages: # optional, default is 
    # A requirements file to install from
    requirements: # optional, default is 
    # A constraints file to use
    constraints: # optional, default is 
    # Don't install package dependencies
    no-deps: # optional, default is false
    # Include prerelease and development versions
    pre: # optional, default is false
    # Install a project in editable mode
    editable: # optional, default is 
    # Only use wheels compatible with a specific platform
    platform: # optional, default is 
    # Upgrade all specified packages to the newest available version
    upgrade: # optional, default is false
    # Extra inputs to pass to pip
    extra: # optional, default is 
          
